### ISSUE TITLE
Fatigue poolMax question

### ISSUE THREAD

**Issue by wolffy-au** [WarLord211/live_in_night_city#4]
More of a question than an issue - do you know why fatigue poolMax in Easy and Hard are 108, while in Normal its 756? (Normal.lua line 99)

**Comment by WarLord211** [comment]
idk  but i increase the easy valve.

**Comment by WarLord211** [comment]
After some research i thing the orginal Programmer forgot to change this valve too.
i will make it 108 in normal too.

https://github.com/FonWasH/live_in_night_city/commit/6e9d03a90324a0827851b8586264f83db84e01fa#diff-ffe84669e2432412d8f7e4bf7d9df516cd268b2c4310ea3c4d438f453832afca

**Comment by wolffy-au** [comment]
Sounds good to me
